### ISSUE TITLE
Issues import bpnet negatives

### ISSUE THREAD

**Issue by Jome0169** [Genentech/gReLU#12]
Hi here,

I'm working through the turtorials and there's an issue when I run the following segment of code from the Training turtorial. The code block 
```python
negatives = grelu.data.preprocess.get_gc_matched_intervals(
    peaks,
    binwidth=0.02, # resolution of measuring GC content
    genome=genome,
    chroms="autosomes", # negative regions will also be chosen from autosomes
    #gc_bw_file='gc_hg38_2114.bw',
    blacklist=genome, # negative regions overlapping the blacklist will be dropped
    seed=0,
)
negatives.head(3)
``` 

outputs the following error: ```ModuleNotFoundError: No module named 'bpnetlite.negatives'```. And this is after bpnet-lite has been install with pip. Any idea how to fix this bug? Either update the function calls in bpnetlite? Or reverting verisons?

**Comment by avantikalal** [comment]
Thanks for raising this @Jome0169 . What version of bpnetlite are you using?

**Comment by Jome0169** [comment]
The current version I have installed is: "0.8.1"

**Comment by avantikalal** [comment]
We are still using 0.5.7 (https://github.com/Genentech/gReLU/blob/main/setup.cfg#L70). You'll need to downgrade bpnetlite to 0.5.7 for this to work.

**Comment by Jome0169** [comment]
This fixed it! Thank you.
