### ISSUE TITLE
Plans for on disk dataloaders?

### ISSUE THREAD

**Issue by mtvector** [Genentech/gReLU#40]
Hi there,

I have been finding the requirement to have your whole dataset in memory a severe limitation for larger models. I'm wondering if you have any plans to implement a version of your dataset and dataloader classes that load from the disk instead of keeping them in memory?

Thanks!
Matthew

**Comment by avantikalal** [comment]
Hi @mtvector. Yes, we totally agree, just haven't gotten around to implementing that yet. Currently there is only this untested experimental branch that you can play around with if you like: https://github.com/Genentech/gReLU/blob/hdf5dataset/src/grelu/data/dataset.py#L1018

**Comment by mtvector** [comment]
Thanks for sharing! I was feeling inspired so I took a first pass at a HDF5-backed BigWig dataset. I'll make a pull request so you can take a look.

**Comment by avantikalal** [comment]
cc @ekageyama
