### ISSUE TITLE
Questions about extracting variants with grelu

### ISSUE THREAD

**Issue by HelloWorldLTY** [Genentech/gReLU#48]
Hi, I am considering use "VariantDataset" function to extract variants, and I notice that this class has many attributions, for example seqs.

If I have a variable named as vr with such class, I found that vr.seqs is not exactly the same as the reference genome. I ensure that I did not add any manual variation here, which also should not be added directly for vr.seqs. vr.seqs also is not purely the same as the reference genome

Therefore, I wonder what is the proper approach to use such class to load variants. I am trying the function (grelu.variant.variant_to_seqs).Thanksa lot.

**Comment by HelloWorldLTY** [comment]
After double checking, I think seqs contain the results after processing. If the variant can be located in such genome, then the variants are loaded. Otherwise, the original reference is perserved. Is it correct? Thanks.

**Comment by avantikalal** [comment]
Hi @HelloWorldLTY , we expect that vr.seqs should correspond to the reference genome sequence surrounding the variant location. Can you post the exact differences that you discovered? Thank you.

**Comment by HelloWorldLTY** [comment]
Hi, may I double check the meaning of "surrounding"? Should it be like (refseq, variant, refseq) or just refseq centered by the variant location?

My method used to extract variants is:

```
vr_ref = VariantDataset(variants = variants,
        seq_len= 512,
        genome= "hg19",
        rc= False,
        max_seq_shift = 0,
        frac_mutation = 0.0)
```

And as I expect, for iteration, vr_ref[0] represents ref and vr_ref[1] represents vr_alt.

However, if I consider vr_ref.seqs, it is not always same as the reference genome.

The same part only happens when the ref is not found in the reference genome, as reported by the default filtering design. If the ref nucl and the corresponding nucl in reference genome are not the same, the variants will not be processed.

Did I explain my problems clear? Or the best approach to extract variant sequence is actually iterating vr_ref?

**Comment by avantikalal** [comment]
Hi, the best approach to extract variant sequence is actually iterating vr_ref. You will get all filtered variants and the dataset output will alternate between reference and alternate alleles.

**Comment by HelloWorldLTY** [comment]
Make sense, thanks a lot!
