### ISSUE TITLE
_check_wandb() throws an error when run on a HPC cluster

### ISSUE THREAD

**Issue by AndreaMariani-AM** [Genentech/gReLU#86]
Dear developers,

Thanks for the great package. I'm running the first tutorial on inference. I'm trying to load the 'borzoi' model. When i run the following code on a HPC cluster

```
model = grelu.resources.load_model(
    project="borzoi",
    model_name="human_fold0",
)
```
I get the following error

```
Traceback (most recent call last):
  File "fine_tune.py", line 8, in <module>
    model = grelu.resources.load_model(
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 247, in load_model
    art = get_artifact(model_name, project, host=host, alias=alias)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 186, in get_artifact
    _check_wandb(host=host)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 74, in _check_wandb
    assert wandb.login(host=host, anonymous="allow"), f'Weights & Biases (wandb) is not configured, see {host}/authorize'
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 76, in login
    if wandb.setup()._settings._noop:
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 383, in setup
    ret = _setup(settings=settings)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 323, in _setup
    wl = _WandbSetup(settings=settings)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 110, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 134, in _settings_setup
    s.update_from_system_config_file()
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 875, in update_from_system_config_file
    setattr(self, key, value)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/pydantic/main.py", line 923, in __setattr__
    self.__pydantic_validator__.validate_assignment(self, name, value)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
anonymous
  Input should be 'allow', 'must' or 'never' [type=literal_error, input_value='true', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/literal_error
```

I have traced back the issue to the call to 

```
_check_wandb()
```

It seems like the the issue is in reaching the wandb API. I have tried with relogging and different defaults for the anonymous param but i get the same error.  It seems that *anonymous* param gets the value of *true*, instead of the specified one.

I have to add that the same procedure run on a local machine runs fine, so i'm suspecting an issue with my own computing cluster. Have you had any similar issues before?

Thanks,
Andrea

### Other info (pip freeze)
```
accelerate==1.0.1
aiohappyeyeballs==2.4.4
aiohttp==3.10.11
aiosignal==1.3.1
anndata==0.9.2
annotated-types==0.7.0
appdirs==1.4.4
async-timeout==5.0.1
attrs==24.2.0
backports.zoneinfo==0.2.1
bioframe==0.7.2
biopython==1.83
biothings-client==0.3.1
bpnet-lite==0.5.7
captum==0.5.0
certifi==2024.8.30
charset-normalizer==3.4.0
click==8.1.7
colorama==0.4.6
contourpy==1.1.1
cycler==0.12.1
discrete-key-value-bottleneck-pytorch==0.1.1
diskcache==5.6.3
docker-pycreds==0.4.0
einops==0.8.0
einx==0.3.0
enformer-pytorch==0.8.10
eval_type_backport==0.2.0
filelock==3.16.1
fonttools==4.55.3
frozendict==2.4.6
frozenlist==1.5.0
fsspec==2024.10.0
genomepy==0.16.1
gitdb==4.0.11
GitPython==3.1.43
gReLU==1.0.2
h5py==3.11.0
hdf5plugin==5.0.0
huggingface-hub==0.26.5
idna==3.10
igraph==0.11.8
importlib_metadata==8.5.0
importlib_resources==6.4.5
Jinja2==3.1.4
joblib==1.4.2
kiwisolver==1.4.7
ledidi==1.2.2
leidenalg==0.10.2
lightning-utilities==0.11.9
llvmlite==0.41.1
logomaker==0.8
loguru==0.7.3
MarkupSafe==2.1.5
matplotlib==3.7.5
mizani==0.9.3
modisco-lite==2.2.1
mpmath==1.3.0
multidict==6.1.0
mygene==3.2.2
mysql-connector-python==9.0.0
natsort==8.4.0
networkx==3.1
norns==0.1.6
nose==1.3.7
numba==0.58.1
numpy==1.24.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.20.5
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
packaging==24.2
pandas==2.0.3
patsy==1.0.1
pillow==10.4.0
platformdirs==4.3.6
plotnine==0.12.4
polars==1.8.2
propcache==0.2.0
protobuf==5.29.1
psutil==6.1.0
pyBigWig==0.3.22
pydantic==2.10.3
pydantic_core==2.27.1
pyfaidx==0.8.1.3
pygenomeviz==0.4.4
pymemesuite==0.1.0a3
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytorch-lightning==2.4.0
pytz==2024.2
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
safetensors==0.4.5
scikit-learn==1.3.2
scipy==1.10.1
seaborn==0.13.2
sentry-sdk==2.19.2
setproctitle==1.3.4
six==1.17.0
smmap==5.0.1
statsmodels==0.14.1
sympy==1.13.3
tangermeme==0.4.2
texttable==1.7.0
threadpoolctl==3.5.0
tokenizers==0.20.3
torch==2.4.1
torchmetrics==1.5.2
tqdm==4.67.1
transformers==4.46.3
triton==3.0.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
vector_quantize_pytorch==1.14.8
wandb==0.19.0
yarl==1.15.2
zipp==3.20.2
```

**Comment by AndreaMariani-AM** [comment]
> Dear developers,
> 
> Thanks for the great package. I'm running the first tutorial on inference. I'm trying to load the 'borzoi' model. When i run the following code on a HPC cluster
> 
> ```
> model = grelu.resources.load_model(
>     project="borzoi",
>     model_name="human_fold0",
> )
> ```
> 
> I get the following error
> 
> ```
> Traceback (most recent call last):
>   File "fine_tune.py", line 8, in <module>
>     model = grelu.resources.load_model(
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 247, in load_model
>     art = get_artifact(model_name, project, host=host, alias=alias)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 186, in get_artifact
>     _check_wandb(host=host)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/resources/__init__.py", line 74, in _check_wandb
>     assert wandb.login(host=host, anonymous="allow"), f'Weights & Biases (wandb) is not configured, see {host}/authorize'
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 76, in login
>     if wandb.setup()._settings._noop:
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 383, in setup
>     ret = _setup(settings=settings)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 323, in _setup
>     wl = _WandbSetup(settings=settings)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 301, in __init__
>     _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 110, in __init__
>     self._settings = self._settings_setup(settings, self._early_logger)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 134, in _settings_setup
>     s.update_from_system_config_file()
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 875, in update_from_system_config_file
>     setattr(self, key, value)
>   File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/pydantic/main.py", line 923, in __setattr__
>     self.__pydantic_validator__.validate_assignment(self, name, value)
> pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
> anonymous
>   Input should be 'allow', 'must' or 'never' [type=literal_error, input_value='true', input_type=str]
>     For further information visit https://errors.pydantic.dev/2.10/v/literal_error
> ```
> 
> I have traced back the issue to the call to
> 
> ```
> _check_wandb()
> ```
> 
> It seems like the the issue is in reaching the wandb API. I have tried with relogging and different defaults for the anonymous param but i get the same error. It seems that _anonymous_ param gets the value of _true_, instead of the specified one.
> 
> I have to add that the same procedure run on a local machine runs fine, so i'm suspecting an issue with my own computing cluster. Have you had any similar issues before?
> 
> Thanks, Andrea
> 
> ### Other info (pip freeze)
> ```
> accelerate==1.0.1
> aiohappyeyeballs==2.4.4
> aiohttp==3.10.11
> aiosignal==1.3.1
> anndata==0.9.2
> annotated-types==0.7.0
> appdirs==1.4.4
> async-timeout==5.0.1
> attrs==24.2.0
> backports.zoneinfo==0.2.1
> bioframe==0.7.2
> biopython==1.83
> biothings-client==0.3.1
> bpnet-lite==0.5.7
> captum==0.5.0
> certifi==2024.8.30
> charset-normalizer==3.4.0
> click==8.1.7
> colorama==0.4.6
> contourpy==1.1.1
> cycler==0.12.1
> discrete-key-value-bottleneck-pytorch==0.1.1
> diskcache==5.6.3
> docker-pycreds==0.4.0
> einops==0.8.0
> einx==0.3.0
> enformer-pytorch==0.8.10
> eval_type_backport==0.2.0
> filelock==3.16.1
> fonttools==4.55.3
> frozendict==2.4.6
> frozenlist==1.5.0
> fsspec==2024.10.0
> genomepy==0.16.1
> gitdb==4.0.11
> GitPython==3.1.43
> gReLU==1.0.2
> h5py==3.11.0
> hdf5plugin==5.0.0
> huggingface-hub==0.26.5
> idna==3.10
> igraph==0.11.8
> importlib_metadata==8.5.0
> importlib_resources==6.4.5
> Jinja2==3.1.4
> joblib==1.4.2
> kiwisolver==1.4.7
> ledidi==1.2.2
> leidenalg==0.10.2
> lightning-utilities==0.11.9
> llvmlite==0.41.1
> logomaker==0.8
> loguru==0.7.3
> MarkupSafe==2.1.5
> matplotlib==3.7.5
> mizani==0.9.3
> modisco-lite==2.2.1
> mpmath==1.3.0
> multidict==6.1.0
> mygene==3.2.2
> mysql-connector-python==9.0.0
> natsort==8.4.0
> networkx==3.1
> norns==0.1.6
> nose==1.3.7
> numba==0.58.1
> numpy==1.24.4
> nvidia-cublas-cu12==12.1.3.1
> nvidia-cuda-cupti-cu12==12.1.105
> nvidia-cuda-nvrtc-cu12==12.1.105
> nvidia-cuda-runtime-cu12==12.1.105
> nvidia-cudnn-cu12==9.1.0.70
> nvidia-cufft-cu12==11.0.2.54
> nvidia-curand-cu12==10.3.2.106
> nvidia-cusolver-cu12==11.4.5.107
> nvidia-cusparse-cu12==12.1.0.106
> nvidia-nccl-cu12==2.20.5
> nvidia-nvjitlink-cu12==12.6.85
> nvidia-nvtx-cu12==12.1.105
> packaging==24.2
> pandas==2.0.3
> patsy==1.0.1
> pillow==10.4.0
> platformdirs==4.3.6
> plotnine==0.12.4
> polars==1.8.2
> propcache==0.2.0
> protobuf==5.29.1
> psutil==6.1.0
> pyBigWig==0.3.22
> pydantic==2.10.3
> pydantic_core==2.27.1
> pyfaidx==0.8.1.3
> pygenomeviz==0.4.4
> pymemesuite==0.1.0a3
> pyparsing==3.1.4
> python-dateutil==2.9.0.post0
> pytorch-lightning==2.4.0
> pytz==2024.2
> PyYAML==6.0.2
> regex==2024.11.6
> requests==2.32.3
> safetensors==0.4.5
> scikit-learn==1.3.2
> scipy==1.10.1
> seaborn==0.13.2
> sentry-sdk==2.19.2
> setproctitle==1.3.4
> six==1.17.0
> smmap==5.0.1
> statsmodels==0.14.1
> sympy==1.13.3
> tangermeme==0.4.2
> texttable==1.7.0
> threadpoolctl==3.5.0
> tokenizers==0.20.3
> torch==2.4.1
> torchmetrics==1.5.2
> tqdm==4.67.1
> transformers==4.46.3
> triton==3.0.0
> typing_extensions==4.12.2
> tzdata==2024.2
> urllib3==2.2.3
> vector_quantize_pytorch==1.14.8
> wandb==0.19.0
> yarl==1.15.2
> zipp==3.20.2
> ```

# UPDATE

The issue is NOT related to the HPC cluster or gReLU. In fact, it can be traced back to the updated to wandb package. 

```
wandb==0.18.7 #works just fine
wandb==0.19.0 #breaks everything
```

I'm closing the issue.

**Comment by AndreaMariani-AM** [comment]
Closing the issue as the updated *wandb* package broke everything

**Comment by ekageyama** [comment]
For a fix, it seems that this is a setting problem from an old version that conflicts with pydantic validation, in old versions `anonymous` could be `True`, leading to the issue, have a check here, and correct it, the allowed values are `'allow', 'must' or 'never'`
~/.config/wandb/settings
