### ISSUE TITLE
Cannot create model through grelu.lightning module for mouse

### ISSUE THREAD

**Issue by AndreaMariani-AM** [Genentech/gReLU#87]
Hi,

Thanks for the great package. I have a question on fine tuning and model creation.
I want to fine tune Borzoi on some data i have that is mouse mm10. 
I'm following tutorial 2 on fine tuning and i can create a `grelu.lightning` model 
```
model_params = {
    'model_type':'BorzoiPretrainedModel', # Type of model
    'n_tasks': 2, 
    'crop_len':0, 
    'n_transformers': 4, 
    'fold': 2 # 0-3 folds i want to use.
}

train_params = {
    'task':'binary', 
    'lr':1e-4, 
    'logger': 'csv', 
    'batch_size': 32, 
    'num_workers': 8,
    'devices': 0, 
    'save_dir': os.path.join(data_dir + '/' + exp),
    'optimizer': 'adam',
    'max_epochs': 2,
    'checkpoint': True, # Save checkpoints
}
model = grelu.lightning.LightningModel(model_params=model_params, train_params=train_params)
```

This model calls then `wandb` to download the state dictionary (output log file)

```
...
wandb: Downloading large artifact human_state_dict_fold2:latest, 907.30MB. 1 files...
...
```
The issue now is when i want to load the mouse_state_dict, which is impossible as it's seems that human is hardcoded:
https://github.com/Genentech/gReLU/blob/efd30819a894c10d7dfda2a111f85825240d52c9/src/grelu/model/models.py#L594

When changed manually in the source code, i get the following error as the model_state_dict is expecting the shape of the human (7611, 1920, 1), but it gets the mouse one (2608, 1920, 1) 

```
Traceback (most recent call last):
  File "/hpcnfs/scratch/DP/amariani/Jbruno/I53S/code/grelu_model/grelu/fine_tune.py", line 98, in <module>
    model = grelu.lightning.LightningModel(model_params=model_params, train_params=train_params)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/lightning/__init__.py", line 87, in __init__
    self.build_model()
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/lightning/__init__.py", line 111, in build_model
    self.model = self.model(
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/grelu/model/models.py", line 548, in __init__
    model.load_state_dict(state_dict)
  File "/hpcnfs/data/DP/software/grelu_venv/grelu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BorzoiModel:
	size mismatch for head.channel_transform.conv.layer.weight: copying a param with shape torch.Size([2608, 1920, 1]) from checkpoint, the shape in current model is torch.Size([7611, 1920, 1]).
	size mismatch for head.channel_transform.conv.layer.bias: copying a param with shape torch.Size([2608]) from checkpoint, the shape in current model is torch.Size([7611]).
```
Any idea on how to fix it or a workaround is highly appreciated.

Thanks for the help.

Best,
Andrea

**Comment by avantikalal** [comment]
Hi @AndreaMariani-AM , happy to help.

First, please see my response here regarding the `PretrainedModel` class types: https://github.com/Genentech/gReLU/issues/72

Next, note that the Borzoi mouse and human models share the same convolutional and transformer layers. Only the head layer is different. Since the `BorzoiPretrainedModel` class initializes only the convolutional and transformer layers from the published weights, it is identical for mouse and human and so we have preset it to human.

If you want to get the full Borzoi model including the head layer pre-trained for mouse, you can do this:
```
import grelu.resources
model = grelu.resources.load_model(
    project="borzoi",
    model_name="mouse_fold0",
)
```

**Comment by AndreaMariani-AM** [comment]
Yes, this is what i was going to do after reading (#72). Thanks again for the clarification and the help @avantikalal 

Best,
Andrea
