### ISSUE TITLE
filter_blacklist doesn't support obtaining custom blacklist from custom genome

### ISSUE THREAD

**Issue by varsh7777** [Genentech/gReLU#9]
Hi,

I want to draw attention to a bug that occurs when I try to use a custom blacklist file for my custom genome when calling `grelu.data.preprocess.filter_blacklist`. The function `get_blacklist_file` is called before `filter_blacklist` can check if I have provided a custom path for the blacklist. After entering `get_blacklist_file`, if a blacklist file associated with the passed in genome does not already exist within the grelu blacklists resources folder, an error is thrown and the function can not continue to check if I have provided a path to a custom blacklist file.

Essentially, the logic in `filter_blacklist` blocks the function from checking if I have provided a custom blacklist. Instead, it only works when users use genomes in the grelu blacklists resources folder. I believe this error would be resolved if the function checked for a custom blacklist first before checking for a blacklist file in the grelu resources. 

Thanks!

**Comment by gokceneraslan** [comment]
Thanks for reporting this @varsh7777 . Can you send a pull request?

**Comment by avantikalal** [comment]
Fixed in #36
